package com.fet.esb.crm.biz.services.crmbillinquirybizservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-12-28T13:49:42.383+08:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://services.biz.crm.esb.fet.com/CRMBillInquiryBizService", name = "CRMBillInquiryBizService")
@XmlSeeAlso({com.tibco.schemas.crm_billingbizservices.sharedresources.xsd.schema.ObjectFactory.class, com.tibco.schemas.crm_billing.sharedresources.xsd.base.imported.schema.ObjectFactory.class, tw.com.fet.itsoa.schemas.common_domain.sharedresources.xsd.base.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CRMBillInquiryBizService {

    @WebResult(name = "queryOfferListResponse", targetNamespace = "http://www.tibco.com/schemas/CRM-BillingBizServices/SharedResources/XSD/Schema.xsd", partName = "Response")
    @WebMethod(action = "/CRM-BillingBizServices/CRMBillInquiryBizService.serviceagent/CRMBillInquiryBizServiceEndpoint2/queryOfferList")
    public com.tibco.schemas.crm_billingbizservices.sharedresources.xsd.schema.QueryOfferListResponse queryOfferList(
        @WebParam(partName = "Request", name = "queryOfferListRequest", targetNamespace = "http://www.tibco.com/schemas/CRM-BillingBizServices/SharedResources/XSD/Schema.xsd")
        com.tibco.schemas.crm_billingbizservices.sharedresources.xsd.schema.QueryOfferListRequest request
    );
}
