package com.fet.esb.crm.biz.services.crmbillinquirybizservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-12-28T13:49:42.390+08:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "CRMBillInquiryBizService", 
                  wsdlLocation = "file:/E:/workspaces/fet-crm/smarthome/src/main/resources/wsdl/SOA_CRM_CRMBillInquiryBizService_0101.wsdl",
                  targetNamespace = "http://services.biz.crm.esb.fet.com/CRMBillInquiryBizService") 
public class CRMBillInquiryBizService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.biz.crm.esb.fet.com/CRMBillInquiryBizService", "CRMBillInquiryBizService");
    public final static QName CRMBillInquiryBizServiceEndpointJMS = new QName("http://services.biz.crm.esb.fet.com/CRMBillInquiryBizService", "CRMBillInquiryBizServiceEndpointJMS");
    public final static QName CRMBillInquiryBizServiceEndpointHTTP = new QName("http://services.biz.crm.esb.fet.com/CRMBillInquiryBizService", "CRMBillInquiryBizServiceEndpointHTTP");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/workspaces/fet-crm/smarthome/src/main/resources/wsdl/SOA_CRM_CRMBillInquiryBizService_0101.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CRMBillInquiryBizService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/workspaces/fet-crm/smarthome/src/main/resources/wsdl/SOA_CRM_CRMBillInquiryBizService_0101.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CRMBillInquiryBizService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CRMBillInquiryBizService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRMBillInquiryBizService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CRMBillInquiryBizService
     */
    @WebEndpoint(name = "CRMBillInquiryBizServiceEndpointJMS")
    public CRMBillInquiryBizService getCRMBillInquiryBizServiceEndpointJMS() {
        return super.getPort(CRMBillInquiryBizServiceEndpointJMS, CRMBillInquiryBizService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMBillInquiryBizService
     */
    @WebEndpoint(name = "CRMBillInquiryBizServiceEndpointJMS")
    public CRMBillInquiryBizService getCRMBillInquiryBizServiceEndpointJMS(WebServiceFeature... features) {
        return super.getPort(CRMBillInquiryBizServiceEndpointJMS, CRMBillInquiryBizService.class, features);
    }
    /**
     *
     * @return
     *     returns CRMBillInquiryBizService
     */
    @WebEndpoint(name = "CRMBillInquiryBizServiceEndpointHTTP")
    public CRMBillInquiryBizService getCRMBillInquiryBizServiceEndpointHTTP() {
        return super.getPort(CRMBillInquiryBizServiceEndpointHTTP, CRMBillInquiryBizService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMBillInquiryBizService
     */
    @WebEndpoint(name = "CRMBillInquiryBizServiceEndpointHTTP")
    public CRMBillInquiryBizService getCRMBillInquiryBizServiceEndpointHTTP(WebServiceFeature... features) {
        return super.getPort(CRMBillInquiryBizServiceEndpointHTTP, CRMBillInquiryBizService.class, features);
    }

}
